apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: curlpod
  name: curlpod
spec:
  containers:
  - args:
    - sleep
    - infinity
    image: curlimages/curl
    name: curlpod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}